apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
  labels:
    app: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
        - name: inference
          image: jeesemm/inference:0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: distilbert-base-uncased-finetuned-sst-2-english
            - name: KAFKA_BOOTSTRAP
              value: host.docker.internal:9093
            - name: RAW_TOPIC
              value: events.raw
            - name: SCORED_TOPIC
              value: events.scored
            - name: GROUP_ID
              value: inference-v1
            - name: PYTHONPATH
              value: /app
          command: ["uvicorn"]
          args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10