apiVersion: v1
kind: Service
metadata:
  name: inference
  labels:
    app: inference
spec:
  selector:
    app: inference
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP